version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - holocraft

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    networks:
      - holocraft

  frontend:
    build: ./dashboard
    ports:
      - "3000:80"
    networks:
      - holocraft

volumes:
  mongo_data:

networks:
  holocraft: